export const projects = [
  {
    id: 1,
    hero_image_link: [
      {
        url: "https://www.applify.com.sg/blog/wp-content/uploads/2022/03/A-pathway-that-UIUX-team-follows-before-designing-your-app.png",
        caption: "This is the caption",
      },
      {
        url: "https://www.liquidplanner.com/wp-content/uploads/2019/04/HiRes-17.jpg",
        caption: "This is the caption",
      },
    ],
    title: "Node API PRoject ",
    sub_title: "A sample project",
    content: "This is the content of the sample project.",
    features: [
      "This is features 1",
      "This is features 2",
      "This is features 3",
      "This is features 1",
    ],
    techStack: ["React", "Angular"],
    date: "2023-10-22T10:00:00.000Z",
    github_link: "https://github.com/sample-project1",
    deployed_link: "https://sample-project1.com",
    blog_link: "https://blog.sample-project1.com",
    tags: ["Web Application"],
    created_at: "2023-10-28T10:06:29.806Z",
    updated_at: "2023-10-28T10:06:29.806Z",
  },
  {
    id: 2,
    hero_image_link: [
      {
        url: "https://www.applify.com.sg/blog/wp-content/uploads/2022/03/A-pathway-that-UIUX-team-follows-before-designing-your-app.png",
        caption: "This is the caption",
      },
      {
        url: "https://www.applify.com.sg/blog/wp-content/uploads/2022/03/A-pathway-that-UIUX-team-follows-before-designing-your-app.png",
        caption: "This is the caption",
      },
    ],
    title: "Node API PRoject ",
    sub_title: "A sample project",
    content: "This is the content of the sample project.",
    features: [
      "This is features 1",
      "This is features 2",
      "This is features 3",
      "This is features 1",
    ],
    techStack: ["React", "Angular"],
    date: "2023-10-22T10:00:00.000Z",
    github_link: "https://github.com/sample-project1",
    deployed_link: "https://sample-project1.com",
    blog_link: "https://blog.sample-project1.com",
    tags: ["Web Application"],
    created_at: "2023-10-28T10:06:29.806Z",
    updated_at: "2023-10-28T10:06:29.806Z",
  },
  {
    id: 3,
    hero_image_link: [
      {
        url: "https://www.applify.com.sg/blog/wp-content/uploads/2022/03/A-pathway-that-UIUX-team-follows-before-designing-your-app.png",
        caption: "This is the caption",
      },
      {
        url: "https://www.applify.com.sg/blog/wp-content/uploads/2022/03/A-pathway-that-UIUX-team-follows-before-designing-your-app.png",
        caption: "This is the caption",
      },
    ],
    title: "Node API PRoject ",
    sub_title: "A sample project",
    content: "This is the content of the sample project.",
    features: [
      "This is features 1",
      "This is features 2",
      "This is features 3",
      "This is features 1",
    ],
    techStack: ["React", "Angular"],
    date: "2023-10-22T10:00:00.000Z",
    github_link: "https://github.com/sample-project1",
    deployed_link: "https://sample-project1.com",
    blog_link: "https://blog.sample-project1.com",
    tags: ["Web Application"],
    created_at: "2023-10-28T10:06:29.806Z",
    updated_at: "2023-10-28T10:06:29.806Z",
  },
  {
    id: 4,
    hero_image_link: [
      {
        url: "https://www.applify.com.sg/blog/wp-content/uploads/2022/03/A-pathway-that-UIUX-team-follows-before-designing-your-app.png",
        caption: "This is the caption",
      },
      {
        url: "https://www.applify.com.sg/blog/wp-content/uploads/2022/03/A-pathway-that-UIUX-team-follows-before-designing-your-app.png",
        caption: "This is the caption",
      },
    ],
    title: "Node API PRoject ",
    sub_title: "A sample project",
    content: "This is the content of the sample project",
    techStack: ["React", "Angular"],
    features: [
      "This is features 1",
      "This is features 2",
      "This is features 3",
      "This is features 1",
    ],
    date: "2023-10-22T10:00:00.000Z",
    github_link: "https://github.com/sample-project1",
    deployed_link: "https://sample-project1.com",
    blog_link: "https://blog.sample-project1.com",
    tags: ["Web Application"],
    created_at: "2023-10-28T10:06:29.806Z",
    updated_at: "2023-10-28T10:06:29.806Z",
  },
];
